[package]
name = "watch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["cargo"] }
crossterm = "0.27.0"
sha2 = "0.10.8"

[profile.release]
opt-level = 3
